name: Java gradle CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install jdk
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Providing gradle execution permission.
      run: chmod +x gradlew

    - name: Build artifact with gradle.
      run: ./gradlew clean bootWar

    - name: Build and push docker image.
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: partha00011/springboot-cicd-ga
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

