name: Java gradle CI

on: workflow_dispatch
  
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]

jobs:

  initialization:
    runs-on: ubuntu-20.04
    steps: 

  # build_artifact:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: install jdk
  #   - uses: actions/setup-java@v3
  #     with:
  #       distribution: 'temurin'
  #       java-version: '17'

  #   - name: Providing gradle execution permission.
  #     run: chmod +x gradlew

  #   - name: Build artifact with gradle.
  #     run: ./gradlew clean bootWar